# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8d31ed5731752dd2dec40973410a9cdbd597a2ae4d40346eeb7eae3fe413fb727940085fb73c1344a8f54f673b7349e0ce572919e42a82c0a8cff4c56a52299

test:
  secret_key_base: 599b84a216a9ed12230d392efee4ee2e9516453cae3fc27a60043de35686e236cb8c073a0aac13962ba9af8c20236fa10c1128b678c5afb4bec94a3dff83d996

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
